// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.1
// source: protocol/proto/ticker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstID   string  `protobuf:"bytes,1,opt,name=instID,proto3" json:"instID,omitempty"`
	BestBid  float64 `protobuf:"fixed64,2,opt,name=bestBid,proto3" json:"bestBid,omitempty"`
	BidSz    float64 `protobuf:"fixed64,3,opt,name=bidSz,proto3" json:"bidSz,omitempty"`
	BestAsk  float64 `protobuf:"fixed64,4,opt,name=bestAsk,proto3" json:"bestAsk,omitempty"`
	AskSz    float64 `protobuf:"fixed64,5,opt,name=askSz,proto3" json:"askSz,omitempty"`
	EventTs  int64   `protobuf:"varint,6,opt,name=eventTs,proto3" json:"eventTs,omitempty"`
	UpdateID int64   `protobuf:"varint,7,opt,name=updateID,proto3" json:"updateID,omitempty"`
}

func (x *TickerInfo) Reset() {
	*x = TickerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_ticker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerInfo) ProtoMessage() {}

func (x *TickerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_ticker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerInfo.ProtoReflect.Descriptor instead.
func (*TickerInfo) Descriptor() ([]byte, []int) {
	return file_protocol_proto_ticker_proto_rawDescGZIP(), []int{0}
}

func (x *TickerInfo) GetInstID() string {
	if x != nil {
		return x.InstID
	}
	return ""
}

func (x *TickerInfo) GetBestBid() float64 {
	if x != nil {
		return x.BestBid
	}
	return 0
}

func (x *TickerInfo) GetBidSz() float64 {
	if x != nil {
		return x.BidSz
	}
	return 0
}

func (x *TickerInfo) GetBestAsk() float64 {
	if x != nil {
		return x.BestAsk
	}
	return 0
}

func (x *TickerInfo) GetAskSz() float64 {
	if x != nil {
		return x.AskSz
	}
	return 0
}

func (x *TickerInfo) GetEventTs() int64 {
	if x != nil {
		return x.EventTs
	}
	return 0
}

func (x *TickerInfo) GetUpdateID() int64 {
	if x != nil {
		return x.UpdateID
	}
	return 0
}

var File_protocol_proto_ticker_proto protoreflect.FileDescriptor

var file_protocol_proto_ticker_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01,
	0x0a, 0x0a, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x6e, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e,
	0x73, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x62, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x69, 0x64, 0x53, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62,
	0x69, 0x64, 0x53, 0x7a, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x65, 0x73, 0x74, 0x41, 0x73, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x62, 0x65, 0x73, 0x74, 0x41, 0x73, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x73, 0x6b, 0x53, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x61,
	0x73, 0x6b, 0x53, 0x7a, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x44, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protocol_proto_ticker_proto_rawDescOnce sync.Once
	file_protocol_proto_ticker_proto_rawDescData = file_protocol_proto_ticker_proto_rawDesc
)

func file_protocol_proto_ticker_proto_rawDescGZIP() []byte {
	file_protocol_proto_ticker_proto_rawDescOnce.Do(func() {
		file_protocol_proto_ticker_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_ticker_proto_rawDescData)
	})
	return file_protocol_proto_ticker_proto_rawDescData
}

var file_protocol_proto_ticker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_proto_ticker_proto_goTypes = []interface{}{
	(*TickerInfo)(nil), // 0: TickerInfo
}
var file_protocol_proto_ticker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_proto_ticker_proto_init() }
func file_protocol_proto_ticker_proto_init() {
	if File_protocol_proto_ticker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_ticker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_ticker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_ticker_proto_goTypes,
		DependencyIndexes: file_protocol_proto_ticker_proto_depIdxs,
		MessageInfos:      file_protocol_proto_ticker_proto_msgTypes,
	}.Build()
	File_protocol_proto_ticker_proto = out.File
	file_protocol_proto_ticker_proto_rawDesc = nil
	file_protocol_proto_ticker_proto_goTypes = nil
	file_protocol_proto_ticker_proto_depIdxs = nil
}
